### ISSUE TITLE
Support for GCC 4.9.2 - codecvt not supported

### ISSUE THREAD

**Issue by n36510** [libAthena/Athena#29]
<pre>[  1%] Building CXX object CMakeFiles/AthenaCore.dir/src/Athena/FileReader.cpp.o
In file included from /home/mew/Desktop/Athena-2.3.0/include/Athena/FileReader.hpp:7:0,
                 from /home/mew/Desktop/Athena-2.3.0/src/Athena/FileReader.cpp:1:
/home/mew/Desktop/Athena-2.3.0/include/Athena/IStreamReader.hpp:5:19: fatal error: codecvt: No such file or directory
 #include &lt;codecvt&gt;
                   ^
compilation terminated.
CMakeFiles/AthenaCore.dir/build.make:77: recipe for target 'CMakeFiles/AthenaCore.dir/src/Athena/FileReader.cpp.o' failed
make[2]: *** [CMakeFiles/AthenaCore.dir/src/Athena/FileReader.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/AthenaCore.dir/all' failed
make[1]: *** [CMakeFiles/AthenaCore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by Antidote** [comment]
Kinda odd that the one operating system to have this issue is a Linux Distro. Jack is on it at the moment.

**Comment by jackoalan** [comment]
OK, I removed the wstring_convert and codecvt header in #30.. should be merged once we confirm I didn't break anything

**Comment by jackoalan** [comment]
#31 has been merged and all <codecvt> includes removed.. 

Thanks for the report!
